### ISSUE TITLE
ValueError: Invalid BLAST database: hgtdb/blast/db.

### ISSUE THREAD

**Issue by sarah872** [qiyunlab/HGTector#46]
Hi, I am having troubles running HGTector with blast:

I downloaded the database from dropbox and ran this command:
`makeblastdb -dbtype prot -in db.faa -out blast/db -title db -parse_seqids -taxid_map taxon.map`

However, when running `search`, I am getting an error:

````
hgtector search -i proteins.fasta -o test -m blast -p 8 -d hgtdb/blast/db -t hgtdb/taxdump/
Homology search started at 2020-03-17 11:59:51.025748.
Traceback (most recent call last):
  File "/home/user/bin/hgtector", line 4, in <module>
    __import__('pkg_resources').run_script('hgtector==2.0b1', 'hgtector')
  File "/home/user/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/home/user/lib/python3.7/site-packages/hgtector-2.0b1-py3.7.egg/EGG-INFO/scripts/hgtector", line 100, in <module>
    main()
  File "/home/user/lib/python3.7/site-packages/hgtector-2.0b1-py3.7.egg/EGG-INFO/scripts/hgtector", line 39, in main
    module(args)
  File "/home/user/lib/python3.7/site-packages/hgtector-2.0b1-py3.7.egg/hgtector/search.py", line 131, in __call__
    self.args_wf(args)
  File "/home/user/lib/python3.7/site-packages/hgtector-2.0b1-py3.7.egg/hgtector/search.py", line 285, in args_wf
    blast_db = self.check_blast()
  File "/home/user/lib/python3.7/site-packages/hgtector-2.0b1-py3.7.egg/hgtector/search.py", line 507, in check_blast
    .format(db_))
ValueError: Invalid BLAST database: hgtdb/blast/db.
````

Also, these commands are failing:
````
hgtector search -i proteins.fasta -o test -m blast -p 8 -d hgtdb/blast/db. -t hgtdb/taxdump/
hgtector search -i proteins.fasta -o test -m blast -p 8 -d hgtdb/blast/ -t hgtdb/taxdump/
hgtector search -i proteins.fasta -o test -m blast -p 8 -d hgtdb/blast/db.faa -t hgtdb/taxdump/
````

**Comment by vmreyes12** [comment]
I'm experiencing this exact same problem. 
The database constructed itself correctly, but when I tell the program to go to said database, it does not.

**Comment by qiyunzhu** [comment]
Hello @vmreyes12 @sarah872 Thank you for reporting this. I just did a test of BLAST db construction and didn't see the error mentioned by @sarah872 . I guess the mostly likely causes are:

1) Database path issue. What files did you see under `hgtdb/blast`? In a normal case, there should be these files: `db.phr`, `db.pin`, `db.pog`, `db.psd`, `db.psi`, `db.psq`. If that's the case, the command `-d hgtdb/blast/db` should probably work.

2) BLAST version is usually not a problem, as long as `makeblastdb` and `blastp` belong to the same BLAST package. I just tried BLAST 2.9.0+ and it worked fine. If you suspect that the currently deployed BLAST executables may be problematic, you may install a local copy by:
```
conda install -c bioconda blast
```
This won't interfere with the existing copy. It only works in the current conda environment. You may test to see if it resolves the problem. Hope this helps!

**Comment by vmreyes12** [comment]
The files I have under hgtdb/blast are all indexed with numbers in the format of `db.00n.phr` as well as pin, pog, psd, psi, and psq. Don't know if that messes up the code somehow? I used the database you provide in your docs to compile the blastdb.

The cluster I was working on had blast 2.7.0 (didn't have admin privileges to upgrade), and when I switched over to DIAMOND, and I tried to run the following basic DIAMOND command:
`diamond blastx -d nr -q reads.fna -o matches.m8`
The error code spat out that I used a newer version of DIAMOND to construct the database, and the code could not read the file because of that. I installed the most recent version of DIAMOND to my conda environment, and it solved the problem. 
I assumed something similar may have happened in my blast run, but I'm not 100% certain. 

Thanks for getting back to us!

**Comment by qiyunzhu** [comment]
Hi @vmreyes12 You are welcome! DIAMOND does have more strict requirement of version, because its database format has changed since a recent version. For BLAST I doubt so. I know that NCBI recently phased out BLAST database format v4 and embraced v5 as the new default, but newer BLAST should work with v4 databases without problem.

By `00n` you meant that `n` is an incremental number? If so that's normal, because BLAST split a database in multiple volumes. But if `db.00n` is the exact string prefixing every file, then you should do `hgtdb/blast/db.00n` instead of `hgtdb/blast/db`.

**Comment by qiyunzhu** [comment]
Let me close this issue is no more updates.

**Comment by lanlan0210** [comment]
> Hi @vmreyes12 You are welcome! DIAMOND does have more strict requirement of version, because its database format has changed since a recent version. For BLAST I doubt so. I know that NCBI recently phased out BLAST database format v4 and embraced v5 as the new default, but newer BLAST should work with v4 databases without problem.
> 
> By `00n` you meant that `n` is an incremental number? If so that's normal, because BLAST split a database in multiple volumes. But if `db.00n` is the exact string prefixing every file, then you should do `hgtdb/blast/db.00n` instead of `hgtdb/blast/db`.
The blast/ folder contains files from db.00.(db.phr, db.pin, db.pog, db.psd, db.psi, db.psq) to db.44.(db.phr, db.pin, db.pog, db.psd, db.psi, db.psi. Db. psq), when running hgtector search -i proteins.fasta -o test -m blast -p 8 -d hgtdb/blast/db -t hgtdb/taxdump/, which number of db should be selected? -d hgtdb/blast/db will report an error, but -d hgtdb/blast/db.00 or -d hgtdb/blast/db.44 will not report an error (replacing db with any number between db00 and db44 will work fine), So in this case, which number should you choose?
