### ISSUE TITLE
ValueError: Invalid self-alignment method: None.

### ISSUE THREAD

**Issue by sarah872** [qiyunlab/HGTector#70]
Hi,
I was trying out the newest release `2.0b3` and the tutorial (second run).
```
hgtector search -i o55h7.faa.gz -o . -m diamond -d ref107/diamond/db.dmnd -t ref107/taxdump/
```

I am getting the following error:
```
Homology search started at 2020-12-28 14:00:52.356490.
Traceback (most recent call last):
  File "/home/user/python-venv/bin/hgtector", line 4, in <module>
    __import__('pkg_resources').run_script('hgtector==2.0b3', 'hgtector')
  File "/home/user/python-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/python-venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/home/user/python-venv/lib/python3.7/site-packages/hgtector-2.0b3-py3.7.egg/EGG-INFO/scripts/hgtector", line 96, in <module>
  File "/home/user/python-venv/lib/python3.7/site-packages/hgtector-2.0b3-py3.7.egg/EGG-INFO/scripts/hgtector", line 35, in main
  File "/home/user/python-venv/lib/python3.7/site-packages/hgtector-2.0b3-py3.7.egg/hgtector/search.py", line 131, in __call__
    def usearch5(query, db, type, out, threads = '4', evalue = '100', alignment = 'local'):
  File "/home/user/python-venv/lib/python3.7/site-packages/hgtector-2.0b3-py3.7.egg/hgtector/search.py", line 380, in args_wf
ValueError: Invalid self-alignment method: None.
```

**Comment by qiyunzhu** [comment]
Hello @sarah872 Thank you for reporting this issue. I think the most plausible reason is that the [configuration file](https://github.com/qiyunlab/HGTector/blob/master/doc/config.md) is missing or corrupt. If you installed HGTector using conda, this file should be at:

```
/home/user/miniconda3/envs/hgtector/lib/python3.7/site-packages/hgtector/config.yml
```

However it appears that you did it using **venv** instead of conda. I am not familar with venv though. Perhaps the current installation method cannot link the program to the configuration file in a venv environment.

Would it be possible if you try again using one of the two installation methods described in the [documentation](https://github.com/qiyunlab/HGTector/blob/master/doc/install.md#installation-1) and let me know if the problem is solved?

**Comment by sarah872** [comment]
Thank you, running the test data worked now after a conda-installation!

I've noticed that the tutorial only points to `<ref107>/diamond/db` but should be instead `<ref107>/diamond/db.dmnd`. Also, the database that I downloaded from dropbox needs to be indexed first with `diamond makedb -d hgtdb/db.faa --threads 10`, right?

**Comment by qiyunzhu** [comment]
@sarah872 I am glad that it worked for you!

That command without `.dmnd` should be fine. DIAMOND will automatically add this extension if not specified. I tested with the old v0.9.26 and the latest v2.0.6 and both worked in that way.

You are right that the big standard database you downloaded from Dropbox needs to be indexed first. But the actual command for doing so is bit more complicated. Please find the instruction [here](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md#Manual-compiling).

**Comment by sarah872** [comment]
thank you!
