### ISSUE TITLE
Can't download pre-compiled database from dropbox

### ISSUE THREAD

**Issue by zhuxiaoyu123** [qiyunlab/HGTector#82]
Hi,
I am trying to download the pre-compiled database from dropbox, but it is too big to download, which may due to the slow Internet connection. The download can be started but it dosen't seem to be working. I was told that the download will be fininshed three days later. I do not  know why the speed is so low. I do not know whether other users meet the same problems. BTW, can i use wget to download the database?

Xiaoyu

**Comment by zhuxiaoyu123** [comment]
Hi,

That is great. To be honest, i have tried to use  hgtector several times since last year. However, i gave up every time because of the database. Upload your database in another platform is a good solution. Thanks a lot.

xiaoyu

**Comment by qiyunzhu** [comment]
Hello @zhuxiaoyu123 I have updated the program so that it can download the latest NCBI data without problem. I also updated the pre-built database to Nov 2021. However it is still hosted at Dropbox. If you still experience difficulty in downloading, please email me and we can find a way to transfer large files.

**Comment by zhuxiaoyu123** [comment]
Hi,

Many thanks. I have found out why i can not download the file. The reason is Dropbox is not available in China. Thus, I downloaded the new database with VPN.

Best wishes,
Xiaoyu

**Comment by qiyunzhu** [comment]
@zhuxiaoyu123 Glad to know that you were able to download the database!
