### ISSUE TITLE
ValueError: Invalid BLAST database: hgtdb/blast/db.

### ISSUE THREAD

**Issue by advbactres** [qiyunlab/HGTector#90]
Dear qiyunlab
I'm trying to create and compile the pre-built database using ncbi blast version 2.10.0+.
1. As mention in a similar issue you mention that the compiled database must have db.phr, db.pin, db.pog, db.psd, db.psi, db.psq, but in my case the compiled database has phr,pin,pog and psq files only.

2. Seraching  bunch of protein sequences using
hgtector search -i uni.fasta -o . -m blast -d hgtdb/blast/db -t hgtdb/taxdump/ command gives following error

-bash-4.2$ hgtector search -i uni.fasta -o . -m blast -d hgtdb/blast/db -t hgtdb/taxdump/
Homology search started at 2022-03-11 15:54:33.549462.
Traceback (most recent call last):
  File "/usr/local/bin/hgtector", line 4, in <module>
    __import__('pkg_resources').run_script('hgtector==2.0b3', 'hgtector')
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/EGG-INFO/scripts/hgtector", line 96, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/EGG-INFO/scripts/hgtector", line 35, in main
    module(args)
  File "/usr/local/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/search.py", line 131, in __call__
    self.args_wf(args)
  File "/usr/local/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/search.py", line 284, in args_wf
    blast_db = self.check_blast()
  File "/usr/local/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/search.py", line 497, in check_blast
    raise ValueError(f'Invalid BLAST database: {db}.')
ValueError: Invalid BLAST database: hgtdb/blast/db.

3. I have tried compiling and searching with both the pre compiled versions (2019 and 2021) of database but the same error persists. 
4. I have tried compiling the pre built database with DIAMOND 0.9.36, but i get 
Error: Invalid taxonomy mapping file format.

5. I tried compiling a custome database with 25 protein sequences and then seraching the same sequences as .fasta, this seems to work at database search but during "analyse"  , i get this result
  raise ValueError(f'Cannot auto-infer taxonomy for {sid}.'
ValueError: Cannot auto-infer taxonomy for uni. Please specify manually.

Can you please help me out, how to go about these errors.
![Screenshot from 2022-03-11 17-06-18](https://user-images.githubusercontent.com/101397106/157860162-b3d6946b-ffd3-4bbe-9814-fd5421cddc73.png)
![Screenshot from 2022-03-11 17-05-38](https://user-images.githubusercontent.com/101397106/157860176-00c89bdb-7fdd-4924-a23b-42f4779c0a33.png)
![Screenshot from 2022-03-11 17-04-35](https://user-images.githubusercontent.com/101397106/157860183-ee6722f2-cef2-4dea-b9c8-d28ce3a424a0.png)
![Screenshot from 2022-03-11 17-03-59](https://user-images.githubusercontent.com/101397106/157860188-ecabeecc-fd74-4b54-8a6d-9a2dd4ce6837.png)

**Comment by qiyunzhu** [comment]
Hello @advbactres Thank you for reporting this issue.

I guess that the database path `hgtdb/blast/db` may not be correct. You can check that by typing `ls hgtdb/blast/db.phr`. Note that `db` is not a directory, but the stem filename of the database files. If in your case it is a directory, then you need to do `hgtdb/blast/db/db`.

***

For DIAMOND, someone reported a related [issue](#76). It is sometimes due to the inconsistency between DIAMOND version (which changed multiple times) and NCBI format. According to the HGTector [documentation](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md), you can try to compile it manually:

```bash
echo $'accession.version\ttaxid' | cat - <(zcat taxon.map.gz) > prot.accession2taxid.FULL
diamond makedb --threads 16 --in db.faa --taxonmap prot.accession2taxid.FULL --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp --db diamond/db
rm prot.accession2taxid.FULL
```

And provide the screen output so that I can further debug.

***

The possible reason your custom 25-protein database doesn't work is because it does not contain taxonomy information, or the taxonomy information is inconsistent between the database and the taxdump.

**Comment by advbactres** [comment]
Hello @qiyunzhu , Thank you for the reply
1. As you mentioned "**hgtdb/blast/db**" is pointing to the database files named db, and not the directory. I have database files named as db, eg db.06.pin. 

2. i have followed the steps as mentioned in the documentation, for both the instances ie blast and diamond. For DIAMOND command  "diamond makedb --threads 16 --in db.faa --taxonmap prot.accession2taxid.FULL --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp --db diamond/db"

i get the error Error: Invalid taxonomy mapping file format. 

![diamond_error2](https://user-images.githubusercontent.com/101397106/158118599-cb67c53b-e566-4e2b-8219-c7607c8d72d1.png)
![diamond_error](https://user-images.githubusercontent.com/101397106/158118607-56034439-0c75-41fc-94e3-b733e4d438b4.png)

3. For the custom database,  i had used uniprot sequences, which lacked taxonomy information, so i understand why the error occured.

**Comment by qiyunzhu** [comment]
@advbactres Thanks for sharing more information. I see. Perhaps there is some compatibility issue between the latest NCBI taxonomy mapping file and the BLAST/DIAMOND commands used in HGTector. I know that DIAMOND has had some taxonomy issue in the past. Not sure about the latest versions. Let me do some testing to catch the latest trends.

**Comment by qiyunzhu** [comment]
@advbactres Could you please try DIAMOND 2.0+ ([here](https://github.com/bbuchfink/diamond/releases)) to see if the problem is solved?

DIAMOND is known to have dependency issues which blocks the installation of latest versions via Conda. So you may need to download the binary or compile from source. The database formats of 2.0.x and 0.9.x are different. I suspect that is the reason.

Meanwhile I will check the BLAST issue.

**Comment by advbactres** [comment]
@qiyunzhu , thanks for the suggestion, it worked with diamond 2.0+

I had one more query .
I had manually downloaded microbe genome sequences from NCBI, using the url file that is created by hgtector database with ---manual option. I then used wget to download the sequences into a folder named database. 
There were approximately 36000 genomes that were downloaded from NCBI. When I ran the 'database'  command without --manual, the program automatically detects the sequences, but is unable to extract all the genomes into database.aa file and the process automatically stops with a KILL signal. 
I assume that since there is around 30GB of data the extraction fails so to avoid this,  I have manually extracted and formatted the database.aa file (>header with single line sequences) as required by the hgtector but since the database process ends abruptly it doesn't downloads the "taxon.map.gz" file. required for database creation.
Is there a way to get the taxon.map.gz for the sequences that I have downloaded before the extraction process begins or if I could create the file myself and pass it to the program when creating the database ??

**Comment by qiyunzhu** [comment]
@advbactres Thanks for the update. I believe that you can manually generate a database without triggering HGTector. In this way, you can work around limitations of memory and disk space.

This `taxon.map.gz` thing is merely a protein ID to TaxID mapping file. You can generate it by yourself. Basically, every protein ID is mapped to the taxonomy ID of the host genome.  (There used to be duplicated protein IDs in NCBI. I guess they are gone now.).

Also, as long as your DIAMOND or BLASTP database has taxonomy built-in (see instruction for [manual compiling](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md#manual-compiling)), you literally don't need `taxon.map.gz`, because HGTector will extract taxIDs from the database when it calls DIAMOND or BLAST.

**Comment by advbactres** [comment]
@qiyunzhu Thanks a lot. I really appreciate your help.
